### ISSUE TITLE
`oc.get_file` 出现 `FileNotFoundError`

### ISSUE THREAD

**Issue by Gabrielvon** [NovelResearchInvestment/pyocclient#1]
如下报错

```
oc.put_file(remote_path='test_dir/remote_file.txt', local_source_file='local_file.txt')
Out[17]: True
oc.list('test_dir')
Out[18]: [File(path=/test_dir/remote_file.txt,file_type=file,attributes={'{DAV:}getlastmodified': 'Wed, 23 Aug 2023 05:30:33 GMT', '{DAV:}getcontentlength': '4', '{DAV:}resourcetype': None, '{DAV:}getetag': '"5d2dbe3dd0d81f3d1c803ca305cf2356"', '{DAV:}getcontenttype': 'text/plain'})]
oc.check_remote_path('test_dir/remote_file.txt')
Out[19]: True
oc.get_file(remote_path='test_dir/remote_file.txt', local_file='local_file.txt')
Traceback (most recent call last):
  File "......\nri-38\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-6dcdf1773104>", line 1, in <module>
    oc.get_file(remote_path='test_dir/remote_file.txt', local_file='local_file.txt')
  File "......\pyocclient\owncloud\owncloud.py", line 530, in get_file
    raise FileNotFoundError(f"get_file function error: Remote file {remote_path} not exist, please check!")
FileNotFoundError: get_file function error: Remote file /test_dir/remote_file.txt not exist, please check!
```

**Comment by lzb13612** [comment]
> 如下报错
> 
> ```
> oc.put_file(remote_path='test_dir/remote_file.txt', local_source_file='local_file.txt')
> Out[17]: True
> oc.list('test_dir')
> Out[18]: [File(path=/test_dir/remote_file.txt,file_type=file,attributes={'{DAV:}getlastmodified': 'Wed, 23 Aug 2023 05:30:33 GMT', '{DAV:}getcontentlength': '4', '{DAV:}resourcetype': None, '{DAV:}getetag': '"5d2dbe3dd0d81f3d1c803ca305cf2356"', '{DAV:}getcontenttype': 'text/plain'})]
> oc.check_remote_path('test_dir/remote_file.txt')
> Out[19]: True
> oc.get_file(remote_path='test_dir/remote_file.txt', local_file='local_file.txt')
> Traceback (most recent call last):
>   File "......\nri-38\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-20-6dcdf1773104>", line 1, in <module>
>     oc.get_file(remote_path='test_dir/remote_file.txt', local_file='local_file.txt')
>   File "......\pyocclient\owncloud\owncloud.py", line 530, in get_file
>     raise FileNotFoundError(f"get_file function error: Remote file {remote_path} not exist, please check!")
> FileNotFoundError: get_file function error: Remote file /test_dir/remote_file.txt not exist, please check!
> ```

## 报错原因：
1. 对于获取文件方法做了文件检测，需要保证远程路径下拥有test_dir路径，否则报错
2. 由于源码中缺少not，导致判断结果相反，已修复，重新安装该库即可
3. 关于创建文件夹的判断具体可查看 demo 仓库
